-- TRANSACTION_SIGNALS — Stage 0's structuring/velocity detector.
-- Per COUNTERPARTY_ID x day: daily transaction count/amount, z-scored
-- against that counterparty's own trailing 90-day baseline (never including
-- the day being scored). Flags IS_CANDIDATE_STRUCTURING at |z| >= 3 with
-- >=30 days of baseline observed — a counterparty's first month is never
-- flagged, since there isn't enough history yet to know what's normal for
-- them. See sql/detectors/README.md for what this deliberately doesn't do
-- (no near-threshold-clustering heuristic).

USE DATABASE PRAMAN;
USE SCHEMA CORE;

CREATE OR REPLACE VIEW TRANSACTION_SIGNALS AS
WITH daily AS (
  SELECT
    COUNTERPARTY_ID,
    TO_DATE(TXN_TIMESTAMP) AS TXN_DATE,
    COUNT(*)               AS DAILY_TXN_COUNT,
    SUM(AMOUNT)            AS DAILY_TXN_AMOUNT
  FROM TRANSACTIONS
  GROUP BY COUNTERPARTY_ID, TO_DATE(TXN_TIMESTAMP)
),
with_baseline AS (
  SELECT
    COUNTERPARTY_ID,
    TXN_DATE,
    DAILY_TXN_COUNT,
    DAILY_TXN_AMOUNT,
    AVG(DAILY_TXN_COUNT)    OVER (PARTITION BY COUNTERPARTY_ID ORDER BY TXN_DATE
                                   ROWS BETWEEN 90 PRECEDING AND 1 PRECEDING) AS BASELINE_COUNT_MEAN,
    STDDEV(DAILY_TXN_COUNT) OVER (PARTITION BY COUNTERPARTY_ID ORDER BY TXN_DATE
                                   ROWS BETWEEN 90 PRECEDING AND 1 PRECEDING) AS BASELINE_COUNT_STDDEV,
    AVG(DAILY_TXN_AMOUNT)    OVER (PARTITION BY COUNTERPARTY_ID ORDER BY TXN_DATE
                                    ROWS BETWEEN 90 PRECEDING AND 1 PRECEDING) AS BASELINE_AMOUNT_MEAN,
    STDDEV(DAILY_TXN_AMOUNT) OVER (PARTITION BY COUNTERPARTY_ID ORDER BY TXN_DATE
                                    ROWS BETWEEN 90 PRECEDING AND 1 PRECEDING) AS BASELINE_AMOUNT_STDDEV,
    COUNT(*)                 OVER (PARTITION BY COUNTERPARTY_ID ORDER BY TXN_DATE
                                    ROWS BETWEEN 90 PRECEDING AND 1 PRECEDING) AS BASELINE_DAYS_OBSERVED
  FROM daily
)
SELECT
  COUNTERPARTY_ID,
  TXN_DATE,
  DAILY_TXN_COUNT,
  DAILY_TXN_AMOUNT,
  BASELINE_DAYS_OBSERVED,
  ZSCORE(DAILY_TXN_COUNT, BASELINE_COUNT_MEAN, BASELINE_COUNT_STDDEV)   AS VELOCITY_ZSCORE,
  ZSCORE(DAILY_TXN_AMOUNT, BASELINE_AMOUNT_MEAN, BASELINE_AMOUNT_STDDEV) AS AMOUNT_ZSCORE,
  GREATEST(
    ZSCORE(DAILY_TXN_COUNT, BASELINE_COUNT_MEAN, BASELINE_COUNT_STDDEV),
    ZSCORE(DAILY_TXN_AMOUNT, BASELINE_AMOUNT_MEAN, BASELINE_AMOUNT_STDDEV)
  ) AS STRUCTURING_SCORE,
  BASELINE_DAYS_OBSERVED >= 30
    AND GREATEST(
          ZSCORE(DAILY_TXN_COUNT, BASELINE_COUNT_MEAN, BASELINE_COUNT_STDDEV),
          ZSCORE(DAILY_TXN_AMOUNT, BASELINE_AMOUNT_MEAN, BASELINE_AMOUNT_STDDEV)
        ) >= 3
    AS IS_CANDIDATE_STRUCTURING
FROM with_baseline;

GRANT SELECT ON VIEW TRANSACTION_SIGNALS TO ROLE ANALYST_READ;
