-- GL_OUTLIER_SIGNALS — Stage 2's draft-return-vs-filing-history detector.
-- Same method as TRANSACTION_SIGNALS (same ZSCORE UDF), applied to
-- GL_ENTRIES instead: per ACCOUNT_CODE x month, total amount z-scored
-- against a trailing 6-month baseline. LINE_ITEM_MAP.SOURCE_COLUMN traces
-- report line items back to these same ACCOUNT_CODEs, so this is the view
-- assure-return queries to check a draft return figure against the firm's
-- own history. Flags IS_OUTLIER at |z| >= 3 with >=3 months of baseline.

USE DATABASE PRAMAN;
USE SCHEMA CORE;

CREATE OR REPLACE VIEW GL_OUTLIER_SIGNALS AS
WITH monthly AS (
  SELECT
    ACCOUNT_CODE,
    DATE_TRUNC('month', POSTING_DATE)::DATE AS POSTING_MONTH,
    SUM(AMOUNT)                             AS MONTHLY_AMOUNT,
    COUNT(*)                                AS MONTHLY_ENTRY_COUNT
  FROM GL_ENTRIES
  GROUP BY ACCOUNT_CODE, DATE_TRUNC('month', POSTING_DATE)
),
with_baseline AS (
  SELECT
    ACCOUNT_CODE,
    POSTING_MONTH,
    MONTHLY_AMOUNT,
    MONTHLY_ENTRY_COUNT,
    AVG(MONTHLY_AMOUNT)    OVER (PARTITION BY ACCOUNT_CODE ORDER BY POSTING_MONTH
                                  ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) AS BASELINE_MEAN,
    STDDEV(MONTHLY_AMOUNT) OVER (PARTITION BY ACCOUNT_CODE ORDER BY POSTING_MONTH
                                  ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) AS BASELINE_STDDEV,
    COUNT(*)               OVER (PARTITION BY ACCOUNT_CODE ORDER BY POSTING_MONTH
                                  ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) AS BASELINE_MONTHS_OBSERVED
  FROM monthly
)
SELECT
  ACCOUNT_CODE,
  POSTING_MONTH,
  MONTHLY_AMOUNT,
  MONTHLY_ENTRY_COUNT,
  BASELINE_MONTHS_OBSERVED,
  ZSCORE(MONTHLY_AMOUNT, BASELINE_MEAN, BASELINE_STDDEV) AS AMOUNT_ZSCORE,
  BASELINE_MONTHS_OBSERVED >= 3
    AND ABS(ZSCORE(MONTHLY_AMOUNT, BASELINE_MEAN, BASELINE_STDDEV)) >= 3
    AS IS_OUTLIER
FROM with_baseline;

GRANT SELECT ON VIEW GL_OUTLIER_SIGNALS TO ROLE ANALYST_READ;
